import {Component, OnInit, ViewChild} from '@angular/core';

import {AgGridNg2} from 'ag-grid-angular';
import 'ag-grid-enterprise';
import {BsModalService, ModalDirective} from 'ngx-bootstrap/modal';
import {ToastrService} from 'ngx-toastr';
import {MessageService} from '../../shared/shared-service';
import {Subscription} from 'rxjs';

interface clause {
  id?: number;
  footnote?: string;
  shortDesc?: string;
  ibFlag?: any;
  isCustom?: string;
}

@Component({
  selector: 'app-comapany-hedge-reports',
  templateUrl: './reports-comapany-hedge.component.html',
  styleUrls: ['./reports-comapany-hedge.component.scss']
})

export class ReportsComapanyHedgeComponent implements OnInit {
  @ViewChild('agGrid') agGrid: AgGridNg2;
  @ViewChild('modal') modal: ModalDirective;

  selectedClause: clause = {};

  modalTitle = 'HedgeClause Details';

  appliedThemeClassOnTable = 'ag-theme-balham';
  b = {
    id: '1',
    company: 'Acacia Mining PLC',
    ticker: 'ACA',
    exchange: 'L', a1: '', b1: '', c1: '', a2: '', b2: '', c2: '', d2: '', e2: '', f2: '', g2: 'X', a3: '', b3: '', c3: '',
    a4: '', b4: '', c4: '', a5: '', b5: '', a6: '', b6: '', a7: '', a8: '', a9: '', a10: '', a11: '', a12: '', a13: '',
    a14: '', cd15: '', cd17: '', c38: '', cd59: '', universe: 'US', status: 'A',
  };

  columnDefs = [
    {headerName: 'Company', field: 'Company', width: 15, filter: 'agTextColumnFilter', pivot: true, suppressMovable: true},
    {headerName: 'Ticker', field: 'ticker', width: 15, filter: 'agTextColumnFilter', pivot: true, suppressMovable: true},
    {headerName: 'Exchange', field: 'exchange', width: 15, filter: 'agTextColumnFilter', pivot: true, suppressMovable: true},
    {headerName: '1a', field: 'a1', width: 5, filter: false, pivot: true, suppressMovable: true},
    {headerName: '1b', field: 'b1', width: 5, filter: false, pivot: true, suppressMovable: true},
    {headerName: '1c', field: 'c1', width: 5, filter: false, pivot: true, suppressMovable: true},
    {headerName: '2a', field: 'a2', width: 5, filter: false, pivot: true, suppressMovable: true},
    {headerName: '2b', field: 'b2', width: 5, filter: false, pivot: true, suppressMovable: true},
    {headerName: '2c', field: 'c2', width: 5, filter: false, pivot: true, suppressMovable: true},
    {headerName: '2d', field: 'd2', width: 5, filter: false, pivot: true, suppressMovable: true},
    {headerName: '2e', field: 'e2', width: 5, filter: false, pivot: true, suppressMovable: true},
    {headerName: '2f', field: 'f2', width: 5, filter: false, pivot: true, suppressMovable: true},
    {headerName: '2g', field: 'g2', width: 5, filter: false, pivot: true, suppressMovable: true},
    {headerName: '3a', field: 'a3', width: 5, filter: false, pivot: true, suppressMovable: true},
    {headerName: '3b', field: 'b3', width: 5, filter: false, pivot: true, suppressMovable: true},
    {headerName: '3c', field: 'c3', width: 5, filter: false, pivot: true, suppressMovable: true},
    {headerName: '4a', field: 'a4', width: 5, filter: false, pivot: true, suppressMovable: true},
    {headerName: '4b', field: 'b4', width: 5, filter: false, pivot: true, suppressMovable: true},
    {headerName: '4c', field: 'c4', width: 5, filter: false, pivot: true, suppressMovable: true},
    {headerName: '5a', field: 'a5', width: 5, filter: false, pivot: true, suppressMovable: true},
    {headerName: '5b', field: 'b5', width: 5, filter: false, pivot: true, suppressMovable: true},
    {headerName: '6a', field: 'a6', width: 5, filter: false, pivot: true, suppressMovable: true},
    {headerName: '6b', field: 'b6', width: 5, filter: false, pivot: true, suppressMovable: true},
    {headerName: '7a', field: 'a7', width: 5, filter: false, pivot: true, suppressMovable: true},
    {headerName: '8a', field: 'a8', width: 5, filter: false, pivot: true, suppressMovable: true},
    {headerName: '9a', field: 'a9', width: 5, filter: false, pivot: true, suppressMovable: true},
    {headerName: '10a', field: 'a10', width: 5, filter: false, pivot: true, suppressMovable: true},
    {headerName: '11a', field: 'a11', width: 5, filter: false, pivot: true, suppressMovable: true},
    {headerName: '12a', field: 'a12', width: 5, filter: false, pivot: true, suppressMovable: true},
    {headerName: '13a', field: 'a13', width: 5, filter: false, pivot: true, suppressMovable: true},
    {headerName: '14a', field: 'a14', width: 5, filter: false, pivot: true, suppressMovable: true},
    {headerName: 'cd15', field: '15cd', width: 5, filter: false, pivot: true, suppressMovable: true},
    {headerName: 'cd17', field: '17cd', width: 5, filter: false, pivot: true, suppressMovable: true},
    {headerName: 'cd38', field: '38cd', width: 5, filter: false, pivot: true, suppressMovable: true},
    {headerName: 'cd59', field: '59cd', width: 5, filter: false, pivot: true, suppressMovable: true},
    {headerName: 'Universe', field: 'universe', width: 5, filter: false, pivot: true, suppressMovable: true},
    {headerName: 'status', field: 'status', width: 5, filter: false, pivot: true, suppressMovable: true},
  ];

  defaultColDef = {
    sortable: true,
    filter: true,
    resizable: true
  };
  gridApis = [];
  gridApi;
  gridColumnApi;

  rowData: any = [
    {
      id: '1',
      company: 'Acacia Mining PLC',
      ticker: 'ACA',
      exchange: 'L',
      a1: '',
      b1: '',
      c1: '',
      a2: '',
      b2: '',
      c2: '',
      d2: '',
      e2: '',
      f2: '',
      g2: 'X',
      a3: '',
      b3: '',
      c3: '',
      a4: '',
      b4: '',
      c4: '',
      a5: '',
      b5: '',
      a6: '',
      b6: '',
      a7: '',
      a8: '',
      a9: '',
      a10: '',
      a11: '',
      a12: '',
      a13: '',
      a14: '',
      cd15: '',
      cd17: '',
      c38: '',
      cd59: '',
      universe: 'US',
      status: 'A',

    },
    {

      id: '2',
      company: 'Acadian Timber CorP.',
      ticker: 'ADN',
      exchange: 'TO',
      a1: '',
      b1: '',
      c1: '',
      a2: '',
      b2: '',
      c2: '',
      d2: '',
      e2: '',
      f2: '',
      g2: 'X',
      a3: '',
      b3: '',
      c3: '',
      a4: '',
      b4: '',
      c4: '',
      a5: '',
      b5: '',
      a6: '',
      b6: '',
      a7: '',
      a8: '',
      a9: '',
      a10: '',
      a11: '',
      a12: '',
      a13: '',
      a14: '',
      cd15: '',
      cd17: '',
      c38: '',
      cd59: '',
      universe: 'US',
      status: 'A',

    },

    {

      id: '3',
      company: 'Acerus Pharmaceuticals Corporation',
      ticker: 'ASP',
      exchange: 'TO',
      a1: '',
      b1: '',
      c1: '',
      a2: '',
      b2: '',
      c2: '',
      d2: '',
      e2: '',
      f2: '',
      g2: 'X',
      a3: '',
      b3: '',
      c3: '',
      a4: '',
      b4: '',
      c4: '',
      a5: '',
      b5: '',
      a6: '',
      b6: '',
      a7: '',
      a8: '',
      a9: '',
      a10: '',
      a11: '',
      a12: '',
      a13: '',
      a14: '',
      cd15: '',
      cd17: '',
      c38: '',
      cd59: '',
      universe: 'US',
      status: 'P',

    },


    {

      id: '4',
      company: 'Advantage Oil & Gas Ltd.',
      ticker: 'AAV',
      exchange: 'TO',
      a1: '',
      b1: '',
      c1: '',
      a2: '',
      b2: '',
      c2: '',
      d2: '',
      e2: '',
      f2: '',
      g2: 'X',
      a3: '',
      b3: '',
      c3: '',
      a4: '',
      b4: '',
      c4: '',
      a5: '',
      b5: '',
      a6: '',
      b6: '',
      a7: '',
      a8: '',
      a9: '',
      a10: '',
      a11: '',
      a12: '',
      a13: '',
      a14: '',
      cd15: '',
      cd17: '',
      c38: '',
      cd59: '',
      universe: 'US',
      status: 'A',

    },
    {

      id: '5',
      company: 'Aecon Group Inc.',
      ticker: 'ARE',
      exchange: 'TO',
      a1: '',
      b1: '',
      c1: '',
      a2: 'X',
      b2: '',
      c2: 'X',
      d2: '',
      e2: 'X',
      f2: '',
      g2: 'X',
      a3: '',
      b3: '',
      c3: '',
      a4: '',
      b4: '',
      c4: '',
      a5: '',
      b5: '',
      a6: '',
      b6: '',
      a7: '',
      a8: '',
      a9: '',
      a10: '',
      a11: '',
      a12: '',
      a13: '',
      a14: '',
      cd15: '',
      cd17: '',
      c38: '',
      cd59: '',
      universe: 'US',
      status: 'A',

    },


    {

      id: '6',
      company: 'Ag Growth International Inc.',
      ticker: 'AFN',
      exchange: 'TO',
      a1: '',
      b1: '',
      c1: '',
      a2: 'X',
      b2: '',
      c2: 'X',
      d2: '',
      e2: 'X',
      f2: '',
      g2: 'X',
      a3: '',
      b3: '',
      c3: '',
      a4: '',
      b4: '',
      c4: '',
      a5: '',
      b5: '',
      a6: '',
      b6: '',
      a7: '',
      a8: '',
      a9: '',
      a10: '',
      a11: '',
      a12: '',
      a13: '',
      a14: '',
      cd15: '',
      cd17: '',
      c38: '',
      cd59: '',
      universe: 'US',
      status: 'A',

    },


    {

      id: '7',
      company: 'AGF Management Limited',
      ticker: 'AGF.B',
      exchange: 'TO',
      a1: '',
      b1: '',
      c1: '',
      a2: '',
      b2: '',
      c2: '',
      d2: '',
      e2: '',
      f2: '',
      g2: 'X',
      a3: '',
      b3: '',
      c3: '',
      a4: '',
      b4: '',
      c4: '',
      a5: '',
      b5: '',
      a6: '',
      b6: '',
      a7: '',
      a8: '',
      a9: '',
      a10: '',
      a11: '',
      a12: '',
      a13: 'X',
      a14: '',
      cd15: '',
      cd17: '',
      c38: '',
      cd59: '',
      universe: 'US',
      status: 'A',

    },


    {

      id: '8',
      company: 'Agnico Eagle Mines Limited',
      ticker: 'AEM',
      exchange: 'N',
      a1: '',
      b1: '',
      c1: '',
      a2: '',
      b2: '',
      c2: '',
      d2: '',
      e2: '',
      f2: '',
      g2: 'X',
      a3: '',
      b3: '',
      c3: '',
      a4: '',
      b4: '',
      c4: '',
      a5: '',
      b5: '',
      a6: '',
      b6: '',
      a7: 'X',
      a8: '',
      a9: '',
      a10: '',
      a11: '',
      a12: '',
      a13: '',
      a14: '',
      cd15: '',
      cd17: '',
      c38: '',
      cd59: '',
      universe: 'US',
      status: 'A',

    },


    {

      id: '9',
      company: 'AGT Food and Ingredients Inc.',
      ticker: 'AGT',
      exchange: 'TO',
      a1: '',
      b1: '',
      c1: '',
      a2: '',
      b2: '',
      c2: '',
      d2: '',
      e2: '',
      f2: '',
      g2: 'X',
      a3: '',
      b3: '',
      c3: '',
      a4: '',
      b4: '',
      c4: '',
      a5: '',
      b5: '',
      a6: '',
      b6: '',
      a7: 'X',
      a8: '',
      a9: '',
      a10: '',
      a11: '',
      a12: '',
      a13: '',
      a14: '',
      cd15: '',
      cd17: '',
      c38: '',
      cd59: '',
      universe: 'US',
      status: 'A',

    },


    {

      id: '10',
      company: 'Air Canada.',
      ticker: 'AC',
      exchange: 'TO',
      a1: '',
      b1: '',
      c1: '',
      a2: '',
      b2: '',
      c2: '',
      d2: '',
      e2: '',
      f2: '',
      g2: 'X',
      a3: '',
      b3: '',
      c3: '',
      a4: '',
      b4: '',
      c4: '',
      a5: '',
      b5: '',
      a6: '',
      b6: '',
      a7: '',
      a8: '',
      a9: '',
      a10: '',
      a11: '',
      a12: '',
      a13: '',
      a14: '',
      cd15: '',
      cd17: '',
      c38: 'X',
      cd59: '',
      universe: 'US',
      status: 'A',

    },


    {

      id: '11',
      company: 'AirBoss of America Corp.',
      ticker: 'BOS',
      exchange: 'TO',
      a1: '',
      b1: '',
      c1: '',
      a2: '',
      b2: '',
      c2: '',
      d2: '',
      e2: '',
      f2: '',
      g2: 'X',
      a3: '',
      b3: '',
      c3: '',
      a4: '',
      b4: '',
      c4: '',
      a5: '',
      b5: '',
      a6: '',
      b6: '',
      a7: '',
      a8: '',
      a9: '',
      a10: '',
      a11: '',
      a12: '',
      a13: '',
      a14: '',
      cd15: '',
      cd17: '',
      c38: '',
      cd59: '',
      universe: 'US',
      status: 'A',

    },


    {

      id: '12',
      company: 'Alacer Gold Corp.',
      ticker: 'ASR',
      exchange: 'TO',
      a1: '',
      b1: '',
      c1: '',
      a2: '',
      b2: '',
      c2: '',
      d2: '',
      e2: '',
      f2: '',
      g2: 'X',
      a3: '',
      b3: '',
      c3: '',
      a4: '',
      b4: '',
      c4: '',
      a5: '',
      b5: '',
      a6: '',
      b6: '',
      a7: '',
      a8: '',
      a9: '',
      a10: '',
      a11: '',
      a12: '',
      a13: '',
      a14: '',
      cd15: '',
      cd17: '',
      c38: '',
      cd59: '',
      universe: 'US',
      status: 'A',

    },


    {

      id: '13',
      company: 'Alamos Gold Inc.',
      ticker: 'AGI',
      exchange: 'TO',
      a1: '',
      b1: '',
      c1: '',
      a2: '',
      b2: '',
      c2: '',
      d2: '',
      e2: '',
      f2: '',
      g2: 'X',
      a3: '',
      b3: '',
      c3: '',
      a4: '',
      b4: '',
      c4: '',
      a5: '',
      b5: '',
      a6: '',
      b6: '',
      a7: '',
      a8: '',
      a9: '',
      a10: '',
      a11: '',
      a12: '',
      a13: '',
      a14: '',
      cd15: '',
      cd17: '',
      c38: '',
      cd59: '',
      universe: 'US',
      status: 'A',

    },


    {

      id: '14',
      company: 'Alaris Royalty Corp.',
      ticker: 'AD',
      exchange: 'TO',
      a1: '',
      b1: '',
      c1: '',
      a2: '',
      b2: '',
      c2: '',
      d2: '',
      e2: '',
      f2: '',
      g2: 'X',
      a3: '',
      b3: '',
      c3: '',
      a4: '',
      b4: '',
      c4: '',
      a5: '',
      b5: '',
      a6: '',
      b6: '',
      a7: '',
      a8: '',
      a9: '',
      a10: '',
      a11: '',
      a12: '',
      a13: '',
      a14: '',
      cd15: '',
      cd17: '',
      c38: '',
      cd59: '',
      universe: 'US',
      status: 'A',

    },


    {

      id: '15',
      company: 'Alcanna Inc.',
      ticker: 'CLIQ',
      exchange: 'TO',
      a1: '',
      b1: '',
      c1: '',
      a2: '',
      b2: '',
      c2: '',
      d2: '',
      e2: '',
      f2: '',
      g2: 'X',
      a3: '',
      b3: '',
      c3: '',
      a4: '',
      b4: '',
      c4: '',
      a5: '',
      b5: '',
      a6: '',
      b6: '',
      a7: '',
      a8: '',
      a9: '',
      a10: '',
      a11: '',
      a12: '',
      a13: '',
      a14: '',
      cd15: '',
      cd17: '',
      c38: '',
      cd59: '',
      universe: 'US',
      status: 'A',

    },


    {

      id: '16',
      company: 'Algonquin Power & Utilities Corp.',
      ticker: 'AQN',
      exchange: 'N',
      a1: '',
      b1: '',
      c1: '',
      a2: 'X',
      b2: '',
      c2: 'X',
      d2: '',
      e2: 'X',
      f2: '',
      g2: 'X',
      a3: '',
      b3: '',
      c3: '',
      a4: '',
      b4: '',
      c4: '',
      a5: '',
      b5: '',
      a6: '',
      b6: '',
      a7: '',
      a8: '',
      a9: '',
      a10: '',
      a11: '',
      a12: '',
      a13: '',
      a14: '',
      cd15: '',
      cd17: '',
      c38: '',
      cd59: '',
      universe: 'US',
      status: 'A',

    },


    {

      id: '17',
      company: 'Alimentation Couche-Tard Inc.',
      ticker: 'ATD.B',
      exchange: 'TO',
      a1: '',
      b1: '',
      c1: '',
      a2: '',
      b2: '',
      c2: '',
      d2: '',
      e2: '',
      f2: '',
      g2: 'X',
      a3: '',
      b3: '',
      c3: '',
      a4: '',
      b4: '',
      c4: '',
      a5: '',
      b5: '',
      a6: '',
      b6: '',
      a7: 'X',
      a8: '',
      a9: '',
      a10: '',
      a11: '',
      a12: 'X',
      a13: '',
      a14: '',
      cd15: '',
      cd17: '',
      c38: '',
      cd59: '',
      universe: 'US',
      status: 'A',

    },


    {

      id: '18',
      company: 'Allied Properties Real Estate Investment Trust.',
      ticker: 'AP.UN',
      exchange: 'TO',
      a1: '',
      b1: '',
      c1: '',
      a2: 'X',
      b2: '',
      c2: 'X',
      d2: '',
      e2: 'X',
      f2: '',
      g2: 'X',
      a3: '',
      b3: '',
      c3: '',
      a4: '',
      b4: '',
      c4: '',
      a5: '',
      b5: '',
      a6: '',
      b6: '',
      a7: '',
      a8: '',
      a9: '',
      a10: '',
      a11: '',
      a12: '',
      a13: '',
      a14: '',
      cd15: '',
      cd17: '',
      c38: '',
      cd59: '',
      universe: 'US',
      status: 'A',

    },


    {

      id: '19',
      company: 'AltaGas Canada Inc.',
      ticker: 'ACI',
      exchange: 'TO',
      a1: '',
      b1: '',
      c1: '',
      a2: 'X',
      b2: '',
      c2: 'X',
      d2: '',
      e2: 'X',
      f2: '',
      g2: 'X',
      a3: '',
      b3: '',
      c3: '',
      a4: '',
      b4: '',
      c4: '',
      a5: '',
      b5: '',
      a6: '',
      b6: '',
      a7: 'X',
      a8: '',
      a9: '',
      a10: '',
      a11: '',
      a12: '',
      a13: '',
      a14: '',
      cd15: '',
      cd17: '',
      c38: '',
      cd59: '',
      universe: 'US',
      status: 'A',

    },


    {

      id: '20',
      company: 'AltaGas ltd.',
      ticker: 'ALA',
      exchange: 'TO',
      a1: '',
      b1: '',
      c1: '',
      a2: '',
      b2: '',
      c2: '',
      d2: '',
      e2: '',
      f2: '',
      g2: 'X',
      a3: '',
      b3: '',
      c3: '',
      a4: '',
      b4: '',
      c4: '',
      a5: '',
      b5: '',
      a6: '',
      b6: '',
      a7: 'X',
      a8: '',
      a9: '',
      a10: '',
      a11: '',
      a12: '',
      a13: '',
      a14: '',
      cd15: '',
      cd17: '',
      c38: '',
      cd59: '',
      universe: 'US',
      status: 'A',

    },


    {

      id: '21',
      company: 'Altus Group limited.',
      ticker: 'AIF',
      exchange: 'TO',
      a1: '',
      b1: '',
      c1: '',
      a2: '',
      b2: '',
      c2: '',
      d2: '',
      e2: '',
      f2: '',
      g2: 'X',
      a3: '',
      b3: '',
      c3: '',
      a4: '',
      b4: '',
      c4: '',
      a5: '',
      b5: '',
      a6: '',
      b6: '',
      a7: '',
      a8: '',
      a9: '',
      a10: '',
      a11: '',
      a12: '',
      a13: '',
      a14: '',
      cd15: '',
      cd17: '',
      c38: '',
      cd59: '',
      universe: 'US',
      status: 'A',

    },


    {

      id: '22',
      company: 'American Hotal Income Properties REIT LP',
      ticker: 'HOT.U',
      exchange: 'TO',
      a1: '',
      b1: '',
      c1: '',
      a2: '',
      b2: '',
      c2: '',
      d2: '',
      e2: '',
      f2: '',
      g2: 'X',
      a3: '',
      b3: '',
      c3: '',
      a4: '',
      b4: '',
      c4: '',
      a5: '',
      b5: '',
      a6: '',
      b6: '',
      a7: '',
      a8: '',
      a9: '',
      a10: '',
      a11: '',
      a12: '',
      a13: '',
      a14: '',
      cd15: '',
      cd17: '',
      c38: '',
      cd59: '',
      universe: 'US',
      status: 'A',

    },


    {

      id: '23',
      company: 'American Hotal Income Properties REIT LP',
      ticker: 'ANTO',
      exchange: 'L',
      a1: '',
      b1: '',
      c1: '',
      a2: '',
      b2: '',
      c2: '',
      d2: '',
      e2: '',
      f2: '',
      g2: 'X',
      a3: '',
      b3: '',
      c3: '',
      a4: '',
      b4: '',
      c4: '',
      a5: '',
      b5: '',
      a6: '',
      b6: '',
      a7: '',
      a8: '',
      a9: '',
      a10: '',
      a11: '',
      a12: '',
      a13: '',
      a14: '',
      cd15: '',
      cd17: '',
      c38: '',
      cd59: '',
      universe: 'US',
      status: 'P',

    },

  ];
  selectedRowsPerPage = 13;
  customFlag = true;
  active = true;
  subscription: Subscription;
  constructor(private modalService: BsModalService, private toastr: ToastrService,
              private messageService: MessageService) {
    this.subscription = this.messageService.getMessage().subscribe(message => {
      setTimeout(() => {
        this.gridApis.map((api) => {
          api.sizeColumnsToFit();
        });
      }, 500);
    });
  }

  openModal() {
    this.modal.show();
  }

  closeModal() {
    this.modal.hide();
  }

  addNewClause() {
    this.selectedClause = {};
    this.modalTitle = 'New Custom Footnote';
    this.openModal();
  }

  editClause() {
    this.modalTitle = 'Edit Custom Footnote';
    this.openModal();
  }

  saveFootnote() {
    if (!this.selectedClause.id) {
      this.selectedClause.id = this.rowData.length;
      this.rowData = [this.selectedClause, ...this.rowData];
      this.closeModal();

      return;
    }

    this.rowData = this.rowData.map((row) => {
      if (row.id === this.selectedClause.id) {
        row = this.selectedClause;
      }

      return row;
    });

    this.closeModal();
  }

  onGridReady(params) {
    this.gridApi = params.api;
    this.gridApis.push(params.api);
    this.gridColumnApi = params.columnApi;
  }

  onFirstDataRendered(params) {
    params.api.sizeColumnsToFit();
  }

  ngOnInit() {
  }

  go() {
    this.toastr.success('<span>' +
      '<i class="icofont icofont-check-circled pr-2"></i>'
      + 'Fetched data Successfully' +
      '</span>', '',
      {
        closeButton: true,
        enableHtml: true
      }
    );
  }
}
